### ISSUE TITLE
how to import table in jupyter notebook

### ISSUE THREAD

**Issue by 23bca292** [vtcbca/internal-exam-23bca292#2]
how to add table from sqlite to jupyter notebook

**Comment by 23bca264** [comment]
EXAMPLE :
f=open('#location_or_path_of_file','r')

**Comment by 23bca292** [comment]
ok thank you 
i will use this

**Comment by 23bca274** [comment]
> how to add table from sqlite to jupyter notebook


Use following syntax :- 

import csv

with open("location_of csv file","r")as f:
    r=csv.reader(f)
    for row in r:
        print(row)

With above syntax you can export your table and print the records in jupyter notebook.

@23bca292

**Comment by 23bca292** [comment]
okk i understood
